### ISSUE TITLE
Create/Edit Product Page

### ISSUE THREAD

**Issue by yulia99** [khandragon/groupG-soen341project2022#52]
Front end, user stories #31 #32

**Comment by Dinferno-lol** [comment]
This page is accessible to all logged in users and allows them to add products to the online store or modify the details of an existing product. The details needed are an image of the product, the product's description, the product's category and name, and the product's price. Any other info that would be displayed when the product is created or modified is taken from the user's profile (like where the shipping address and who the seller is).
